### ISSUE TITLE
database.nosql ??

### ISSUE THREAD

**Issue by dimitrilahaye** [petersirka/nosql#14]
Hi !
What do you mean for the database's path when you write :
```javascript
var nosql = require('nosql').load('/users/petersirka/desktop/database.nosql');
```
What is the extension .nosql ?

**Comment by vinnyfs89** [comment]
Hello. In this case i used it only for test, but it was used to refer the
table document.

Hope it may help you.

Em Seg, 2 de mar de 2015 12:55, dimitrilahaye <notifications@github.com>
escreveu:

**Comment by dimitrilahaye** [comment]
Thanks for the speed answer ;)
But... excuse me, I am new in the noSQL world. How can I create this table document and what it looks like ?

**Comment by dimitrilahaye** [comment]
No answer for a newbie ? ;)

**Comment by petersirka** [comment]
Hi @dimitrilahaye,
you can create DB file like this:

```javascript
var nosql = require('nosql').load('/users/petersirka/desktop/database.nosql');

nosql.insert({ table: 'A', name: 'New document in A' });
nosql.insert({ table: 'B', name: 'New document in B' });
nosql.insert({ table: 'A', name: 'New document in A' });

// Read all documents by table===A
nosql.all(function(doc) {
    return doc.table === 'A';
}, function(docs) {
    console.log(docs);
});
```

Do you understand? NoSQL DB doesn't support tables, you can store only documents.

**Comment by dimitrilahaye** [comment]
So, when you indicate :
```javascript
var nosql = require('nosql').load('/users/petersirka/desktop/database.nosql');
```
the document database.nosql is created ?

**Comment by petersirka** [comment]
Yes :-), try it.

**Comment by dimitrilahaye** [comment]
I will, promise ;)

**Comment by unformatt** [comment]
Hey Peter - So each file is treated as one collection, right? Which is why there is no collection (like mongo) specified here: 

`nosql.insert({...})`

Whereas mongo would be like:

`db.MyCollection.insert({...})`

So a more explanatory example would be:

```
var nosql = require('nosql');
var Users = nosql.load('/users/petersirka/desktop/users.nosql');
var Posts = nosql.load('/users/petersirka/desktop/posts.nosql');
Users.insert({id:1, name:'Peter'});

Posts.insert({id:1, user_id:1, title:"Peter's post", body: "Great post"});
```

Also, there is no automatic ID (aka _id) like mongo, right?

**Comment by petersirka** [comment]
Hi @unformatt,

__Each file is treated as one collection, right?__
> theoretically yes, but better name is "database"

__Which is why there is no collection specified here:__
> nosql creates multiple readers and one writers and this is the problem in `nosql.insert()` and for it is need an instance. It's too complicated for its implementation.

__Also, there is no automatic ID (aka _id) like mongo, right?__
No, documents don't know about their identity. You must create your own, e.g. `{ id: new Date().getTime() }`.

Thanks :+1:
