### ISSUE TITLE
How to use BSON instead of JSON to save data file?

### ISSUE THREAD

**Issue by cuixiping** [petersirka/nosql#25]
BSON supports more data types such as RegExp than JSON and is more efficient to parse/serialize large content object.

**Comment by petersirka** [comment]
Hi @cuixiping,
sorry for delay. Yes BSON is better and faster, but it's `binary` and this is the problem. I use text (plain) mode and you can edit database everywhere and this is the benefit.

This DB is primary targeted into the small projects 👍
