### ISSUE TITLE
What can I use to find a max id [QUESTION]

### ISSUE THREAD

**Issue by biomade** [petersirka/nosql#37]
I see in the sample code, in the documentation for the Builder that find can have builder.between(); 
what other operations can be done? 
I am looking for a max or last.. so I can grab an id and then add one to it for a pseudo autoincrement.

**Comment by biomade** [comment]
I found it [the scalar call] but now I have a different question... along the same lines.
If I can get the max(id) how can I pass it to another insert call?

**Comment by petersirka** [comment]
- __1Q:__ All operations are noted in documentation.
- __2Q:__ in your callback you have to create another call.
