### ISSUE TITLE
builder.contains is not a function

### ISSUE THREAD

**Issue by hellmelt** [petersirka/nosql#45]
I'm using nosql from npm, version 6.1.0.

According to documentation, DatabaseBuilder has a method _contains_. But when I try to use it I get builder.contains is not a function.

E.g. builder.where works as expected.

**Comment by petersirka** [comment]
Hi @hellmelt, `1M` sorry but I didn't update NoSQL module to newest version. It's my plan, but currently I don't have any time for it. The latest version of NoSQL is a part of Total.js framework.

Sorry again 👎

**Comment by hellmelt** [comment]
OK. I installed total.js and require('total.js/nosql'). Means that the rest of total.js will be dead code on the server, but that's ok. Thank's for the advice.
